/**
 * Cross-language DTO contract: consumption tests.
 *
 * The fixtures in `src/__fixtures__/dto/` are generated by the Rust side
 * (`cargo test -p cseq-app dto_fixture`, see `src-tauri/src/main.rs`) as
 * *typed TypeScript literals*, so `pnpm typecheck` already proves that the
 * serialized Rust DTOs satisfy `bridge.ts` field-for-field (missing, extra,
 * and retyped fields all fail).
 *
 * These tests add the runtime half: the real frontend consumers accept the
 * real backend bytes, and the patch document round-trips through `patchIo`
 * unchanged. If one of these fails after regenerating fixtures, the consumer
 * (not the fixture) needs the fix.
 */
import { describe, expect, it } from "vitest";

import type { TransportSnapshot } from "./bridge";
import { transportSnapshotFixture } from "./__fixtures__/dto/transportSnapshot.fixture";
import { subdivisionSwitchPreviewFixture } from "./__fixtures__/dto/subdivisionSwitchPreview.fixture";
import { dumkaGeneratorPreviewFixture } from "./__fixtures__/dto/dumkaGeneratorPreview.fixture";
import {
  createNeutralPatchDocument,
  readPatchDocument,
  PATCH_SCHEMA_VERSION,
  PATCH_APP_ID,
} from "./patchIo";
import {
  filterSeedPathItemsForTrack,
  seedPathTrackMatches,
  selectRealizedRhythmBySpanId,
  selectTimelineRenderLayers,
  timelineEventBelongsToActiveTrack,
  selectActiveParallelTrackPosition,
} from "./timelineModel";

// Built from the same neutral base as the generator test. The committed file
// is also consumed by the Rust validation test, pinning the fork-v1 disk shape
// in both directions.
const patchDocumentFixture: unknown = JSON.parse(
  JSON.stringify(
    createNeutralPatchDocument({
      savedAt: "2026-06-11T12:00:00.000Z",
      seed: 20260611,
      scoreName: "dto-contract-fixture",
      cycleBeats: 4,
    })
  )
);

describe("transport snapshot fixture through real consumers", () => {
  const snapshot: TransportSnapshot = transportSnapshotFixture;

  it("timeline render layer selection accepts the real DTO shape", () => {
    const selection = selectTimelineRenderLayers(
      snapshot,
      snapshot.currentCycle,
      []
    );
    expect(selection.showTransportRenderLayers).toBe(true);
    expect(selection.activeChannelHocketEvents).toHaveLength(1);
  });

  it("parallel-track scoping accepts the real event metadata", () => {
    const position = selectActiveParallelTrackPosition(
      snapshot.parallelTrackPositions,
      "track-1"
    );
    expect(position?.trackName).toBe("Lead");

    for (const event of snapshot.midiDebugEvents) {
      expect(timelineEventBelongsToActiveTrack(event, "track-1")).toBe(true);
      expect(timelineEventBelongsToActiveTrack(event, "track-2")).toBe(false);
    }
  });

  it("realized rhythm selector accepts the real DTO shape and scopes by track", () => {
    // The live rhythm row's playback source: realized spans for the visible
    // cycle + active track. Proves the real backend bytes feed the selector.
    expect(snapshot.realizedRhythmEvents).toHaveLength(1);
    const onTrack = selectRealizedRhythmBySpanId(
      snapshot,
      snapshot.currentCycle,
      "track-1"
    );
    expect([...onTrack.keys()]).toEqual([5]);
    expect(onTrack.get(5)?.spanLen).toBe(4);

    // A different active track must not pick up another track's realized rhythm.
    const otherTrack = selectRealizedRhythmBySpanId(
      snapshot,
      snapshot.currentCycle,
      "track-2"
    );
    expect(otherTrack.size).toBe(0);
  });

  it("seed-path track matching accepts the real seed trace entries", () => {
    expect(snapshot.seedTraceEvents).toHaveLength(1);
    const [trace] = snapshot.seedTraceEvents;
    expect(seedPathTrackMatches(trace!.trackId, "track-1")).toBe(true);
    expect(seedPathTrackMatches(trace!.trackId, "track-2")).toBe(false);
    expect(trace).toMatchObject({
      seed: "9007199254740993",
      baseSeed: "18446744073709551615",
      historyBefore: ["9007199254740992", "9007199254740993"],
      historyAfter: [
        "9007199254740992",
        "9007199254740993",
        "18446744073709551615",
      ],
    });
    expect(
      filterSeedPathItemsForTrack(snapshot.seedTraceEvents, "track-1")
    ).toHaveLength(1);
  });
});

describe("subdivision switch preview fixture semantics", () => {
  const preview = subdivisionSwitchPreviewFixture;

  it("preserves full-width generated history seeds as decimal strings", () => {
    expect(preview.historySeeds).toEqual([
      "9007199254740993",
      "18446744073709551615",
    ]);
  });

  it("resolves the authored request: 6 beats, all gati 7, two sections", () => {
    expect(preview.beats).toHaveLength(6);
    for (const beat of preview.beats) {
      expect(beat.gati).toBe(7);
      expect(beat.effectiveGati).toBe(7);
    }
    const sectionIndexes = [...new Set(preview.beats.map((beat) => beat.sectionIndex))];
    expect(sectionIndexes).toHaveLength(2);
    expect(preview.beats[0]?.sectionStart).toBe(true);
    expect(preview.beats[3]?.sectionStart).toBe(true);
  });

  it("carries the jathi layer the request authored", () => {
    // Jathi 3 tiles each 3-beat gati-7 section (21 matras) without
    // duplicating gati beat starts — a valid, non-trivial accent layer.
    for (const beat of preview.beats) {
      expect(beat.jathi).toBe(3);
    }
    const kinds = new Set(preview.pulseSpans.map((span) => span.kind));
    expect(kinds.has("section")).toBe(true);
    expect(kinds.has("jathiPulse")).toBe(true);
  });

  it("beat geometry is a partition of the cycle", () => {
    let cursor = 0;
    for (const beat of preview.beats) {
      expect(beat.start).toBeCloseTo(cursor, 10);
      cursor = beat.end;
    }
    expect(cursor).toBeCloseTo(1, 10);
  });
});

describe("Dum-Ka directive trace fixture semantics", () => {
  it("carries Rust-owned requested/applied attribution into the TS preview", () => {
    expect(dumkaGeneratorPreviewFixture.trace).toEqual([
      {
        cycle: 13,
        directiveId: 101,
        family: "barlowRemove",
        requested: 2,
        applied: 2,
        skipped: "none",
      },
    ]);
    expect(dumkaGeneratorPreviewFixture.spans).toHaveLength(4);
  });
});

describe("patch document fixture through patchIo", () => {
  it("reads back through readPatchDocument with identity semantics", () => {
    const document = readPatchDocument(patchDocumentFixture);
    expect(document.app).toBe(PATCH_APP_ID);
    expect(document.schemaVersion).toBe(PATCH_SCHEMA_VERSION);
    expect(document.sequencer.cycleBeats).toBe(4);
    expect(document.sequencer.name).toBe("dto-contract-fixture");

    // Normalizing an already-normalized document must be a fixed point —
    // otherwise save/load cycles mutate patches.
    const reread = readPatchDocument(JSON.parse(JSON.stringify(document)));
    expect(reread).toEqual(document);
  });
});
