/**
 * TS mirror of the evolution engine's metric analysis, for the Generator
 * editor's algorithm-insight lanes: Barlow stratification/indispensability
 * (crates/cseq-rhythm/src/generators/dumka/barlow.rs) and the Sioros
 * metrical template (sioros.rs), plus the two display formulas the panels
 * quote (temperature pool widening and the drift-leash budget, both from
 * evolve.rs).
 *
 * Drift guard: `ui/src/__fixtures__/dumka_metrics_contract.json` is
 * generated by the Rust side (`rust_metrics_contract_fixture_matches` in
 * barlow.rs) and `dumkaMetrics.test.ts` pins this mirror against it, the
 * same scheme as the pattern parser contract. These functions are display
 * inputs only — playback never runs through them.
 */
import type { DumkaCompiled } from "./dumkaPattern";

const PRIME_PSI: Record<number, readonly number[]> = {
  2: [1, 0],
  3: [2, 0, 1],
  5: [4, 0, 3, 1, 2],
  7: [6, 0, 4, 2, 5, 1, 3],
};

/** Largest prime factor with a published Ψ table (barlow.rs MAX_STRATUM_PRIME). */
export const DUMKA_MAX_STRATUM_PRIME = 7;

/** Prime factors, largest first (Barlow's stratification order). */
export function factorDescending(value: number): number[] {
  let rest = Math.max(1, Math.floor(value));
  const factors: number[] = [];
  let p = 2;
  while (p * p <= rest) {
    while (rest % p === 0) {
      factors.push(p);
      rest /= p;
    }
    p += 1;
  }
  if (rest > 1) factors.push(rest);
  factors.sort((a, b) => b - a);
  return factors;
}

/** Beats' factors then the Subdivision's; null when a prime has no Ψ table
 * (the engine then plays the seed verbatim instead of guessing). */
export function stratification(
  cycleBeats: number,
  subdivision: number
): number[] | null {
  const strata = [...factorDescending(cycleBeats), ...factorDescending(subdivision)];
  return strata.every((q) => q in PRIME_PSI) ? strata : null;
}

/** Indispensability rank per pulse: unique in 0..len, higher = more
 * indispensable (group starts take the top q ranks by Ψ_q; off-pulses band
 * by the inner rank, ordered by the pickup principle Ψ_q((g+1) mod q)). */
export function indispensability(strata: number[]): number[] {
  if (strata.length === 0) return [0];
  const [q, ...rest] = strata as [number, ...number[]];
  const inner = indispensability(rest);
  const m = inner.length;
  const n = q * m;
  const psi = PRIME_PSI[q]!;
  const ranks = new Array<number>(n);
  for (let g = 0; g < q; g += 1) {
    for (let j = 0; j < m; j += 1) {
      ranks[g * m + j] =
        j === 0 ? n - q + psi[g]! : inner[j]! * q + psi[(g + 1) % q]!;
    }
  }
  return ranks;
}

/** Sioros metrical level per pulse: 0 = cycle start, deeper strata = higher
 * (faster) levels; stratum d creates level d+1 at multiples of its period. */
export function metricalLevels(strata: number[]): number[] {
  const n = Math.max(
    1,
    strata.reduce((product, q) => product * q, 1)
  );
  const levels = new Array<number>(n).fill(strata.length);
  let period = n;
  strata.forEach((q, depth) => {
    period /= q;
    const level = depth + 1;
    for (let slot = 0; slot < n; slot += Math.max(1, period)) {
      levels[slot] = Math.min(levels[slot]!, level);
    }
  });
  levels[0] = 0;
  return levels;
}

/** The level of whole beats: displacement type-0 moves are forbidden at or
 * above it (evolve.rs derives it as factor_descending(beats).len()). */
export function beatLevel(cycleBeats: number): number {
  return factorDescending(cycleBeats).length;
}

/** Temperature pool size over rank-sorted candidates (evolve.rs pool_pick):
 * 0% keeps the strict argmax/argmin, 100% draws over every candidate. */
export function barlowPoolSize(temperature: number, candidates: number): number {
  if (candidates <= 1) return Math.max(0, candidates);
  return 1 + Math.floor((temperature * (candidates - 1)) / 100);
}

/** Drift-leash budget in grid slots (evolve.rs: ⌈leash% × seed onsets⌉). */
export function leashBudget(leashPercent: number, seedOnsets: number): number {
  return Math.floor((leashPercent * seedOnsets + 99) / 100);
}

/** Counts of the figure pair's candidates in the SEED pattern at its
 * required Subdivision: sustains of ≥ 2 slots plus maximal silent runs of
 * ≥ 2 slots are fragmentable; contiguous sounding runs of ≥ 2 onsets are
 * consolidatable. Mirrors figures.rs interval/run scanning for the insight
 * panel's live sentence (display only; the fold recomputes its own). */
export function figureCandidateCounts(compiled: DumkaCompiled): {
  fragmentable: number;
  consolidatable: number;
  longestInterval: number;
} {
  const subdivision = compiled.requiredSubdivision;
  const slots = compiled.totalBeats * subdivision;
  const intervals: Array<{ start: number; len: number }> = [];
  const onsets = compiled.events
    .map((event) => ({
      start: (event.start.num * subdivision) / event.start.den,
      dur: (event.dur.num * subdivision) / event.dur.den,
    }))
    .sort((a, b) => a.start - b.start);
  let cursor = 0;
  let consolidatable = 0;
  let runLength = 1;
  onsets.forEach((onset, index) => {
    if (onset.start > cursor && onset.start - cursor >= 2) {
      intervals.push({ start: cursor, len: onset.start - cursor });
    }
    if (onset.dur >= 2) {
      intervals.push({ start: onset.start, len: onset.dur });
    }
    if (index > 0) {
      const previous = onsets[index - 1]!;
      if (previous.start + previous.dur === onset.start) {
        runLength += 1;
      } else {
        if (runLength >= 2) consolidatable += 1;
        runLength = 1;
      }
    }
    cursor = Math.max(cursor, onset.start + onset.dur);
  });
  if (runLength >= 2) consolidatable += 1;
  if (slots > cursor && slots - cursor >= 2) {
    intervals.push({ start: cursor, len: slots - cursor });
  }
  return {
    fragmentable: intervals.length,
    consolidatable,
    longestInterval: intervals.reduce((max, i) => Math.max(max, i.len), 0),
  };
}

export interface DumkaGridInsight {
  /** Pulses per cycle at the pattern's REQUIRED Subdivision. */
  slots: number;
  strata: number[];
  ranks: number[];
  levels: number[];
  beatLevel: number;
  /** Slot indices that start a sounding onset. */
  onsetSlots: number[];
  /** Slot occupancy including sustains (an Add cannot land here). */
  occupied: boolean[];
  /** Rank-ascending sounding slots: Remove's candidate order. */
  removeOrder: number[];
  /** Rank-descending free slots: Add's candidate order. */
  addOrder: number[];
}

/**
 * Everything the insight lanes draw, or null when the grid's primes exceed
 * the published tables (the caller shows the seed-verbatim notice instead).
 */
export function gridInsight(compiled: DumkaCompiled): DumkaGridInsight | null {
  const subdivision = compiled.requiredSubdivision;
  const strata = stratification(compiled.totalBeats, subdivision);
  if (strata === null) return null;
  const slots = compiled.totalBeats * subdivision;
  const ranks = indispensability(strata);
  const levels = metricalLevels(strata);
  const occupied = new Array<boolean>(slots).fill(false);
  const onsetSlots: number[] = [];
  for (const event of compiled.events) {
    const start = (event.start.num * subdivision) / event.start.den;
    const end = start + (event.dur.num * subdivision) / event.dur.den;
    onsetSlots.push(start);
    for (let slot = start; slot < Math.min(end, slots); slot += 1) {
      occupied[slot] = true;
    }
  }
  const removeOrder = [...onsetSlots].sort((a, b) => ranks[a]! - ranks[b]!);
  const addOrder = Array.from({ length: slots }, (_, slot) => slot)
    .filter((slot) => !occupied[slot])
    .sort((a, b) => ranks[b]! - ranks[a]!);
  return {
    slots,
    strata,
    ranks,
    levels,
    beatLevel: beatLevel(compiled.totalBeats),
    onsetSlots,
    occupied,
    removeOrder,
    addOrder,
  };
}
