/**
 * Built-in synth monitor voice data: General MIDI program/percussion tables,
 * the hybrid preset banks, and voice label helpers. Extracted verbatim from
 * App.tsx (carve-up round 2).
 */
import type { SynthChannelProgram } from "./bridge";
import { clamp, DEFAULT_SYNTH_VOICES, MIDI_CHANNELS } from "./patchIo";

export const GM_PROGRAM_NAMES = [
  "Acoustic Grand Piano",
  "Bright Acoustic Piano",
  "Electric Grand Piano",
  "Honky-tonk Piano",
  "Electric Piano 1",
  "Electric Piano 2",
  "Harpsichord",
  "Clavinet",
  "Celesta",
  "Glockenspiel",
  "Music Box",
  "Vibraphone",
  "Marimba",
  "Xylophone",
  "Tubular Bells",
  "Dulcimer",
  "Drawbar Organ",
  "Percussive Organ",
  "Rock Organ",
  "Church Organ",
  "Reed Organ",
  "Accordion",
  "Harmonica",
  "Tango Accordion",
  "Acoustic Guitar Nylon",
  "Acoustic Guitar Steel",
  "Electric Guitar Jazz",
  "Electric Guitar Clean",
  "Electric Guitar Muted",
  "Overdriven Guitar",
  "Distortion Guitar",
  "Guitar Harmonics",
  "Acoustic Bass",
  "Electric Bass Finger",
  "Electric Bass Pick",
  "Fretless Bass",
  "Slap Bass 1",
  "Slap Bass 2",
  "Synth Bass 1",
  "Synth Bass 2",
  "Violin",
  "Viola",
  "Cello",
  "Contrabass",
  "Tremolo Strings",
  "Pizzicato Strings",
  "Orchestral Harp",
  "Timpani",
  "String Ensemble 1",
  "String Ensemble 2",
  "Synth Strings 1",
  "Synth Strings 2",
  "Choir Aahs",
  "Voice Oohs",
  "Synth Voice",
  "Orchestra Hit",
  "Trumpet",
  "Trombone",
  "Tuba",
  "Muted Trumpet",
  "French Horn",
  "Brass Section",
  "Synth Brass 1",
  "Synth Brass 2",
  "Soprano Sax",
  "Alto Sax",
  "Tenor Sax",
  "Baritone Sax",
  "Oboe",
  "English Horn",
  "Bassoon",
  "Clarinet",
  "Piccolo",
  "Flute",
  "Recorder",
  "Pan Flute",
  "Blown Bottle",
  "Shakuhachi",
  "Whistle",
  "Ocarina",
  "Lead 1 Square",
  "Lead 2 Sawtooth",
  "Lead 3 Calliope",
  "Lead 4 Chiff",
  "Lead 5 Charang",
  "Lead 6 Voice",
  "Lead 7 Fifths",
  "Lead 8 Bass + Lead",
  "Pad 1 New Age",
  "Pad 2 Warm",
  "Pad 3 Polysynth",
  "Pad 4 Choir",
  "Pad 5 Bowed",
  "Pad 6 Metallic",
  "Pad 7 Halo",
  "Pad 8 Sweep",
  "FX 1 Rain",
  "FX 2 Soundtrack",
  "FX 3 Crystal",
  "FX 4 Atmosphere",
  "FX 5 Brightness",
  "FX 6 Texture",
  "FX 7 Echoes",
  "FX 8 Sci-fi",
  "Sitar",
  "Banjo",
  "Shamisen",
  "Koto",
  "Kalimba",
  "Bagpipe",
  "Fiddle",
  "Shanai",
  "Tinkle Bell",
  "Agogo",
  "Steel Drums",
  "Woodblock",
  "Taiko Drum",
  "Melodic Tom",
  "Synth Drum",
  "Reverse Cymbal",
  "Guitar Fret Noise",
  "Breath Noise",
  "Seashore",
  "Tweet",
  "Telephone Ring",
  "Helicopter",
  "Applause",
  "Gunshot",
];
export const GM_PERCUSSION_NOTES = [
  { note: 35, name: "Acoustic Bass Drum" },
  { note: 36, name: "Bass Drum 1" },
  { note: 37, name: "Side Stick" },
  { note: 38, name: "Acoustic Snare" },
  { note: 39, name: "Hand Clap" },
  { note: 40, name: "Electric Snare" },
  { note: 41, name: "Low Floor Tom" },
  { note: 42, name: "Closed Hi-Hat" },
  { note: 43, name: "High Floor Tom" },
  { note: 44, name: "Pedal Hi-Hat" },
  { note: 45, name: "Low Tom" },
  { note: 46, name: "Open Hi-Hat" },
  { note: 47, name: "Low-Mid Tom" },
  { note: 48, name: "Hi-Mid Tom" },
  { note: 49, name: "Crash Cymbal 1" },
  { note: 50, name: "High Tom" },
  { note: 51, name: "Ride Cymbal 1" },
  { note: 52, name: "Chinese Cymbal" },
  { note: 53, name: "Ride Bell" },
  { note: 54, name: "Tambourine" },
  { note: 55, name: "Splash Cymbal" },
  { note: 56, name: "Cowbell" },
  { note: 57, name: "Crash Cymbal 2" },
  { note: 58, name: "Vibraslap" },
  { note: 59, name: "Ride Cymbal 2" },
  { note: 60, name: "High Bongo" },
  { note: 61, name: "Low Bongo" },
  { note: 62, name: "Mute High Conga" },
  { note: 63, name: "Open High Conga" },
  { note: 64, name: "Low Conga" },
  { note: 65, name: "High Timbale" },
  { note: 66, name: "Low Timbale" },
  { note: 67, name: "High Agogo" },
  { note: 68, name: "Low Agogo" },
  { note: 69, name: "Cabasa" },
  { note: 70, name: "Maracas" },
  { note: 71, name: "Short Whistle" },
  { note: 72, name: "Long Whistle" },
  { note: 73, name: "Short Guiro" },
  { note: 74, name: "Long Guiro" },
  { note: 75, name: "Claves" },
  { note: 76, name: "High Wood Block" },
  { note: 77, name: "Low Wood Block" },
  { note: 78, name: "Mute Cuica" },
  { note: 79, name: "Open Cuica" },
  { note: 80, name: "Mute Triangle" },
  { note: 81, name: "Open Triangle" },
];
export const PERCUSSION_RACK_DRUM_NOTES = [
  36, 35, 38, 37, 42, 46, 45, 50, 64, 60, 66, 75, 77, 54, 53, 81,
];
export const HYBRID_SYNTH_PROGRAMS = [
  0, 0, 0, 0, 0, 0, 0, 0, 104, 89, 52, 73, 48, 80, 33, 45,
];
export const HYBRID_SYNTH_DRUM_NOTES = [
  36, 38, 42, 46, 64, 60, 75, 77, 36, 38, 42, 46, 64, 60, 75, 77,
];
export const SYNTH_VOICE_PRESETS: Array<{
  id: string;
  label: string;
  description: string;
  voices: SynthChannelProgram[];
}> = [
  {
    id: "melodic",
    label: "Melodic palette",
    description: "Sixteen GM instruments for hocketed pitched lines.",
    voices: DEFAULT_SYNTH_VOICES,
  },
  {
    id: "percussion",
    label: "Percussion rack",
    description: "Every channel maps to a separate GM drum key.",
    voices: MIDI_CHANNELS.map((channel) => ({
      channel,
      mode: "percussion",
      program: 0,
      drumNote: PERCUSSION_RACK_DRUM_NOTES[channel - 1] ?? 36,
    })),
  },
  {
    id: "hybrid",
    label: "Kit + colors",
    description: "Channels 1-8 are percussion; 9-16 remain melodic.",
    voices: MIDI_CHANNELS.map((channel) => ({
      channel,
      mode: channel <= 8 ? "percussion" : "melodic",
      program: HYBRID_SYNTH_PROGRAMS[channel - 1] ?? 0,
      drumNote: HYBRID_SYNTH_DRUM_NOTES[channel - 1] ?? 36,
    })),
  },
];

export function synthProgramLabel(program: number): string {
  const index = clamp(Math.round(program), 0, 127);
  return `${index + 1}. ${GM_PROGRAM_NAMES[index] ?? `Program ${index + 1}`}`;
}

export function synthDrumLabel(note: number): string {
  const index = clamp(Math.round(note), 0, 127);
  const named = GM_PERCUSSION_NOTES.find((item) => item.note === index)?.name;
  return `${index}. ${named ?? `Percussion key ${index}`}`;
}

export function synthVoiceLabel(voice: SynthChannelProgram): string {
  return voice.mode === "percussion"
    ? `percussion · ${synthDrumLabel(voice.drumNote)}`
    : `melodic · ${synthProgramLabel(voice.program)}`;
}
