[package]
name = "cseq-rhythm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
cseq-model = { path = "../cseq-model" }
num-bigint = "0.4"
num-rational = { workspace = true }
num-traits = "0.2"
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
serde_json = { workspace = true }
