/**
 * Shared representative input for `buildAutomationTargetDefs` — used by both the
 * perf bench (`perf.bench.ts`) and the characterization test
 * (`automationTargets.test.ts`). Empty `rhythmSelectedKeysByLength` makes the
 * builder fall back to the default pattern set per length, so it exercises the
 * full rhythm-matrix loop; pitch/channel are populated to exercise those loops.
 * Complex nested specs come from patchIo defaults.
 */
import {
  DEFAULT_ORNAMENT_VELOCITY,
  DEFAULT_RATCHET_CURVE_WEIGHTS,
  DEFAULT_RATCHET_MODIFIERS,
  DEFAULT_RATCHET_VELOCITY,
} from "../patchIo";

export const benchPitchStates = Array.from({ length: 8 }, (_unused, index) => ({
  pitch: 48 + index * 2,
  label: `p${index}`,
}));

export const automationTargetBuildInput = {
  tempoBpm: 90,
  generatorDensityPercent: 72,
  dumkaEvolutionRate: 0,
  dumkaBarlowTemperature: 0,
  dumkaFillComplexity: 0,
  dumkaDriftLeash: 25,
  dumkaDensityFloor: 0,
  dumkaDensityCeiling: 100,
  synthEnabled: true,
  midiOutputChannel: 1,
  synthPrograms: [],
  cycleTempoFluxEnabled: false,
  cycleTempoFluxMinBpm: 80,
  cycleTempoFluxMaxBpm: 100,
  cycleTempoFluxCurvePoints: [],
  cycleTempoFluxCurveVariance: 0,
  initialWeights: [],
  initialJathiWeights: [],
  initialJathiBhedam: null,
  boundaries: [],
  sectionCountWeights: [],
  seedHistoryWeight: 1,
  seedNewSeedWeight: 1,
  seedMaxHistory: 8,
  singleParameterRhythmicModulation: false,
  scorePitch: 60,
  scoreVelocity: 96,
  beatAccentMin: 0,
  beatAccentMax: 0,
  sectionAccentMin: 0,
  sectionAccentMax: 0,
  jathiAccentMin: 0,
  jathiAccentMax: 0,
  rhythmLength: 4,
  rhythmOrder: "first",
  rhythmSelectedKeysByLength: {},
  rhythmFallback: 0,
  rhythmFallbackMode: "static",
  rhythmFallbackWeightsByLength: {},
  rhythmEntryWeightsByLength: {},
  rhythmWeights: {},
  rhythmHistoryWeight: 1,
  rhythmNewSeedWeight: 1,
  rhythmMaxHistory: 8,
  rhythmTieOverAccentProbability: 0,
  rhythmRestOverAccentProbability: 0,
  rhythmArticulationCells: {},
  arbitrarySubdivisionProbability: 0,
  arbitrarySubdivisionTargets: [],
  arbitrarySubdivisionClumps: [],
  allowTrivialArbitraryPattern: false,
  arbitrarySubdivisionPoolWeightsByLength: {},
  rhythmSpeedWeights: {},
  ratchetEnabled: false,
  ratchetProbability: 0,
  ratchetSpeedMin: 0,
  ratchetSpeedMax: 8,
  ratchetAllowMultiMatra: false,
  ratchetMaxSpanMatras: 1,
  ratchetSpanGateLimits: [],
  ratchetCooldownMatras: 0,
  ratchetTemporalEasing: 0,
  ratchetTemporalEasingProbability: 0,
  ratchetCurveWeights: DEFAULT_RATCHET_CURVE_WEIGHTS,
  ratchetTemporalEasingWeights: {
    humanize: 0,
    humanizeTight: 0,
    humanizeLoose: 0,
    subtleAccelerando: 0,
    subtleRetardando: 0,
    sway: 0,
    lilt: 0,
  },
  ratchetTimeCurvePoints: [],
  ratchetTimeCurveEnabled: false,
  ratchetTimeCurveVariance: 0,
  ratchetTimePresetWeights: {
    drawn: 0,
    flat: 0,
    lineAccel: 0,
    lineDecel: 0,
    expoAccel: 0,
    expoDecel: 0,
    betaBloom: 0,
    betaPinch: 0,
  },
  ratchetTimeInterpolate: false,
  ratchetTimeInterpolationMin: 0,
  ratchetTimeInterpolationMax: 1,
  ratchetVelocity: DEFAULT_RATCHET_VELOCITY,
  ratchetV2: {
    band: {
      rateSlowRef: 9,
      rateFastRef: 25,
      tracking: 0.5,
      bias: 0,
      spread: 0,
      sync: false,
    },
    fill: { mode: "trail", fraction: 0.5 },
    placement: {
      lengthBias: -0.5,
      lengthWindow: null,
      phraseWeights: [1, 0.5],
      spanPosition: { start: 1, mid: 1, end: 1 },
      edgeWeights: {
        accentStart: 1,
        accentEnd: 1,
        sectionStart: 1,
        sectionEnd: 1,
        cycleStart: 1,
        cycleEnd: 1,
      },
      normalize: true,
    },
    velocityContour: { start: -0.5, mid: 0, end: 0.5 },
  },
  ratchetModifiers: DEFAULT_RATCHET_MODIFIERS,
  ratchetPositionModifierEnabled: false,
  ratchetPositionProbabilityStart: 100,
  ratchetPositionProbabilityMid: 100,
  ratchetPositionProbabilityEnd: 100,
  ratchetPositionSpeedStart: 100,
  ratchetPositionSpeedMid: 100,
  ratchetPositionSpeedEnd: 100,
  ratchetInternalRhythmEnabled: false,
  ratchetInternalRhythmMinCount: 2,
  ratchetInternalRhythmMaxCount: 4,
  ornamentEnabled: false,
  ornamentProbability: 0,
  ornamentBeforeBeatWeight: 0,
  ornamentSingleWeight: 0,
  ornamentDoubleWeight: 0,
  ornamentTripleWeight: 0,
  ornamentDuration: 1,
  ornamentCooldown: 0,
  ornamentAllowRests: false,
  ornamentVelocity: DEFAULT_ORNAMENT_VELOCITY,
  delayEnabled: false,
  delayProbability: 0,
  delayMin: 0,
  delayMax: 0,
  delayTuplets: [],
  pitchShaperEnabled: true,
  pitchOrder: "first",
  pitchCollectionTransposition: 0,
  pitchRangeLow: 48,
  pitchRangeHigh: 84,
  pitchStates: benchPitchStates,
  pitchWeights: {},
  pitchFallback: 0,
  pitchFallbackMode: "static",
  pitchFallbackWeights: {},
  pitchEntryWeights: {},
  pitchHistoryWeight: 1,
  pitchNewSeedWeight: 1,
  pitchMaxHistory: 8,
  pitchBoundaryLow: 0,
  pitchBoundaryHigh: 127,
  pitchBoundaryModulo: 12,
  pitchRatchetWholeProbability: 0,
  pitchRatchetPerHitProbability: 0,
  pitchRatchetPreserveFirstHit: true,
  pitchOrnamentWholeProbability: 0,
  pitchOrnamentPerGraceProbability: 0,
  pitchGracePitchEnabled: false,
  pitchGracePitchProbability: 0,
  pitchGracePitchPitches: [],
  pitchGraceTransposeEnabled: false,
  pitchGraceTransposeProbability: 0,
  pitchGraceTransposeUpWeight: 0,
  pitchGraceTransposeDownWeight: 0,
  pitchGraceTransposeIntervals: [],
  pitchTransposeEnabled: false,
  pitchTransposeProbability: 0,
  pitchTransposeDriveChain: false,
  channelHocketEnabled: true,
  channelHocketOrder: "first" as const,
  channelHocketChannels: [1, 2, 3, 4, 5, 6, 7, 8],
  channelHocketFallback: 1,
  channelHocketWeights: {},
  channelHocketFallbackWeights: {},
  channelHocketEntryWeights: {},
  channelHocketHistoryWeight: 1,
  channelHocketNewSeedWeight: 1,
  channelHocketMaxHistory: 8,
  channelHocketWholeProbability: 0,
  channelHocketPerHitProbability: 0,
  channelHocketPreserveFirstHit: true,
  channelHocketOrnamentWholeProbability: 0,
  channelHocketOrnamentPerGraceProbability: 0,
  channelAccentRules: [],
  channelPositionRules: [],
  channelHocketEuclid: {
    placement: "partition" as const,
    steps: 16,
    layers: [
      { channel: 1, pulses: 5, rotation: 0, maxRun: 1, steps: 16, invert: false },
      { channel: 2, pulses: 3, rotation: 2, maxRun: 2, steps: 12, invert: false },
    ],
    reset: "cycle" as const,
    spanAccentMode: "woven" as const,
    spanAccentChannel: null,
  },
};
