// GENERATED by `cargo test -p cseq-app dto_fixture` (UPDATE_DTO_FIXTURES=1).
// Do not edit by hand. This literal is the serialized Rust DTO; the type
// annotation makes `pnpm typecheck` the Rust↔TS drift gate.
import type { GeneratorPreview } from "../../bridge";

export const dumkaGeneratorPreviewFixture: GeneratorPreview = {
  "seed": {
    "seed": "20260611",
    "source": "locked",
    "history": []
  },
  "spans": [
    {
      "spanId": 1,
      "spanLen": 20,
      "cells": [
        {
          "index": 0,
          "start": 0,
          "len": 8,
          "rest": false,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 113
        },
        {
          "index": 1,
          "start": 8,
          "len": 1,
          "rest": false,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 96
        },
        {
          "index": 2,
          "start": 9,
          "len": 6,
          "rest": true,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 96
        },
        {
          "index": 3,
          "start": 15,
          "len": 1,
          "rest": false,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 96
        },
        {
          "index": 4,
          "start": 16,
          "len": 1,
          "rest": false,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 96
        },
        {
          "index": 5,
          "start": 17,
          "len": 3,
          "rest": true,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 96
        }
      ]
    },
    {
      "spanId": 2,
      "spanLen": 20,
      "cells": [
        {
          "index": 0,
          "start": 0,
          "len": 1,
          "rest": false,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 114
        },
        {
          "index": 1,
          "start": 1,
          "len": 7,
          "rest": true,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 96
        },
        {
          "index": 2,
          "start": 8,
          "len": 1,
          "rest": false,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 96
        },
        {
          "index": 3,
          "start": 9,
          "len": 1,
          "rest": true,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 96
        },
        {
          "index": 4,
          "start": 10,
          "len": 6,
          "rest": false,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 96
        },
        {
          "index": 5,
          "start": 16,
          "len": 1,
          "rest": false,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 96
        },
        {
          "index": 6,
          "start": 17,
          "len": 3,
          "rest": true,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 96
        }
      ]
    },
    {
      "spanId": 3,
      "spanLen": 20,
      "cells": [
        {
          "index": 0,
          "start": 0,
          "len": 4,
          "rest": false,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 115
        },
        {
          "index": 1,
          "start": 4,
          "len": 2,
          "rest": true,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 96
        },
        {
          "index": 2,
          "start": 6,
          "len": 4,
          "rest": false,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 96
        },
        {
          "index": 3,
          "start": 10,
          "len": 5,
          "rest": true,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 96
        },
        {
          "index": 4,
          "start": 15,
          "len": 4,
          "rest": false,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 96
        },
        {
          "index": 5,
          "start": 19,
          "len": 1,
          "rest": true,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 96
        }
      ]
    },
    {
      "spanId": 4,
      "spanLen": 20,
      "cells": [
        {
          "index": 0,
          "start": 0,
          "len": 1,
          "rest": false,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 116
        },
        {
          "index": 1,
          "start": 1,
          "len": 3,
          "rest": true,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 96
        },
        {
          "index": 2,
          "start": 4,
          "len": 4,
          "rest": false,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 96
        },
        {
          "index": 3,
          "start": 8,
          "len": 1,
          "rest": false,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 96
        },
        {
          "index": 4,
          "start": 9,
          "len": 1,
          "rest": true,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 96
        },
        {
          "index": 5,
          "start": 10,
          "len": 4,
          "rest": false,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 96
        },
        {
          "index": 6,
          "start": 14,
          "len": 2,
          "rest": true,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 96
        },
        {
          "index": 7,
          "start": 16,
          "len": 1,
          "rest": false,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 96
        },
        {
          "index": 8,
          "start": 17,
          "len": 3,
          "rest": true,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 96
        }
      ]
    }
  ],
  "trace": [
    {
      "cycle": 13,
      "directiveId": 101,
      "family": "barlowRemove",
      "requested": 3,
      "applied": 0,
      "skipped": "none",
      "corridorClamp": {
        "limit": "floor",
        "densityPercent": 20
      }
    }
  ],
  "densityCorridor": {
    "floor": 20,
    "ceiling": 60
  },
  "cycleDistance": {
    "modelVersion": "v1",
    "distanceMilli": 0
  },
  "workingSubdivision": 20,
  "complexityCorridor": {
    "floor": 12000,
    "ceiling": 60000
  },
  "stateComplexityMilli": 43304,
  "stateDepthDiversityMilli": 78214
};
