// GENERATED by `cargo test -p cseq-app dto_fixture` (UPDATE_DTO_FIXTURES=1).
// Do not edit by hand. This literal is the serialized Rust DTO; the type
// annotation makes `pnpm typecheck` the Rust↔TS drift gate.
import type { GeneratorPreview } from "../../bridge";

export const dumkaGeneratorDepthPreviewFixture: GeneratorPreview = {
  "seed": {
    "seed": "20260812",
    "source": "locked",
    "history": []
  },
  "spans": [
    {
      "spanId": 1,
      "spanLen": 3,
      "cells": [
        {
          "index": 0,
          "start": 0,
          "len": 3,
          "rest": false,
          "tiedFromPrevious": false,
          "tiedToNext": false
        }
      ]
    },
    {
      "spanId": 2,
      "spanLen": 3,
      "cells": [
        {
          "index": 0,
          "start": 0,
          "len": 3,
          "rest": true,
          "tiedFromPrevious": false,
          "tiedToNext": false
        }
      ]
    },
    {
      "spanId": 3,
      "spanLen": 3,
      "cells": [
        {
          "index": 0,
          "start": 0,
          "len": 3,
          "rest": false,
          "tiedFromPrevious": false,
          "tiedToNext": false
        }
      ]
    },
    {
      "spanId": 4,
      "spanLen": 3,
      "cells": [
        {
          "index": 0,
          "start": 0,
          "len": 3,
          "rest": true,
          "tiedFromPrevious": false,
          "tiedToNext": false
        }
      ]
    }
  ],
  "trace": [],
  "densityCorridor": {
    "floor": 0,
    "ceiling": 100
  },
  "workingSubdivision": 3,
  "complexityCorridor": {
    "floor": 0,
    "ceiling": 100000
  },
  "stateComplexityMilli": 0,
  "stateDepthDiversityMilli": 0
};
