// GENERATED by `cargo test -p cseq-app dto_fixture` (UPDATE_DTO_FIXTURES=1).
// Do not edit by hand. This literal is the serialized Rust DTO; the type
// annotation makes `pnpm typecheck` the Rust↔TS drift gate.
import type { GeneratorPreview } from "../../bridge";

export const dumkaGeneratorPerceptualPreviewFixture: GeneratorPreview = {
  "seed": {
    "seed": "20260611",
    "source": "locked",
    "history": []
  },
  "spans": [
    {
      "spanId": 1,
      "spanLen": 20,
      "cells": [
        {
          "index": 0,
          "start": 0,
          "len": 15,
          "rest": false,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 113
        },
        {
          "index": 1,
          "start": 15,
          "len": 5,
          "rest": false,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 96
        }
      ]
    },
    {
      "spanId": 2,
      "spanLen": 20,
      "cells": [
        {
          "index": 0,
          "start": 0,
          "len": 10,
          "rest": true,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 114
        },
        {
          "index": 1,
          "start": 10,
          "len": 10,
          "rest": false,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 96
        }
      ]
    },
    {
      "spanId": 3,
      "spanLen": 20,
      "cells": [
        {
          "index": 0,
          "start": 0,
          "len": 4,
          "rest": false,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 115
        },
        {
          "index": 1,
          "start": 4,
          "len": 4,
          "rest": true,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 96
        },
        {
          "index": 2,
          "start": 8,
          "len": 4,
          "rest": false,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 96
        },
        {
          "index": 3,
          "start": 12,
          "len": 4,
          "rest": true,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 96
        },
        {
          "index": 4,
          "start": 16,
          "len": 4,
          "rest": false,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 96
        }
      ]
    },
    {
      "spanId": 4,
      "spanLen": 20,
      "cells": [
        {
          "index": 0,
          "start": 0,
          "len": 4,
          "rest": true,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 116
        },
        {
          "index": 1,
          "start": 4,
          "len": 4,
          "rest": false,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 96
        },
        {
          "index": 2,
          "start": 8,
          "len": 4,
          "rest": true,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 96
        },
        {
          "index": 3,
          "start": 12,
          "len": 4,
          "rest": false,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 96
        },
        {
          "index": 4,
          "start": 16,
          "len": 4,
          "rest": true,
          "tiedFromPrevious": false,
          "tiedToNext": false,
          "velocity": 96
        }
      ]
    }
  ],
  "trace": [
    {
      "cycle": 17,
      "directiveId": 104,
      "family": "rotate",
      "requested": 16,
      "applied": 0,
      "skipped": "exhausted",
      "perceptual": {
        "modelVersion": "v1",
        "actualMilli": 0,
        "targetMilli": 5000,
        "toleranceMilli": 500,
        "reached": false,
        "exhausted": true
      }
    }
  ],
  "densityCorridor": {
    "floor": 0,
    "ceiling": 100
  },
  "cycleDistance": {
    "modelVersion": "v1",
    "distanceMilli": 0
  }
};
