// GENERATED by `cargo test -p cseq-app dto_fixture` (UPDATE_DTO_FIXTURES=1).
// Do not edit by hand. This literal is the serialized Rust DTO; the type
// annotation makes `pnpm typecheck` the Rust↔TS drift gate.
import type { GeneratorPreview } from "../../bridge";

export const dumkaGeneratorDepthPreviewFixture: GeneratorPreview = {
  "seed": {
    "seed": "20260812",
    "source": "locked",
    "history": []
  },
  "spans": [
    {
      "spanId": 1,
      "spanLen": 3,
      "cells": [
        {
          "index": 0,
          "start": 0,
          "len": 3,
          "rest": false,
          "tiedFromPrevious": false,
          "tiedToNext": false
        }
      ]
    },
    {
      "spanId": 2,
      "spanLen": 3,
      "cells": [
        {
          "index": 0,
          "start": 0,
          "len": 1,
          "rest": false,
          "tiedFromPrevious": false,
          "tiedToNext": false
        },
        {
          "index": 1,
          "start": 1,
          "len": 1,
          "rest": true,
          "tiedFromPrevious": false,
          "tiedToNext": false
        },
        {
          "index": 2,
          "start": 2,
          "len": 1,
          "rest": false,
          "tiedFromPrevious": false,
          "tiedToNext": false
        }
      ]
    },
    {
      "spanId": 3,
      "spanLen": 3,
      "cells": [
        {
          "index": 0,
          "start": 0,
          "len": 3,
          "rest": false,
          "tiedFromPrevious": false,
          "tiedToNext": false
        }
      ]
    },
    {
      "spanId": 4,
      "spanLen": 3,
      "cells": [
        {
          "index": 0,
          "start": 0,
          "len": 1,
          "rest": false,
          "tiedFromPrevious": false,
          "tiedToNext": false
        },
        {
          "index": 1,
          "start": 1,
          "len": 1,
          "rest": true,
          "tiedFromPrevious": false,
          "tiedToNext": false
        },
        {
          "index": 2,
          "start": 2,
          "len": 1,
          "rest": false,
          "tiedFromPrevious": false,
          "tiedToNext": false
        }
      ]
    }
  ],
  "trace": [
    {
      "cycle": 1,
      "directiveId": 9007199254740991,
      "family": "stochastic",
      "requested": 8,
      "applied": 0,
      "skipped": "projection",
      "corridorClamp": {
        "limit": "floor",
        "densityPercent": 50
      }
    }
  ],
  "densityCorridor": {
    "floor": 50,
    "ceiling": 50,
    "floorMilli": 50000,
    "ceilingMilli": 50000
  },
  "cycleDistance": {
    "modelVersion": "v1",
    "distanceMilli": 33881
  },
  "workingSubdivision": 3,
  "complexityCorridor": {
    "floor": 0,
    "ceiling": 100000
  },
  "stateComplexityMilli": 33333,
  "stateDepthDiversityMilli": 91829,
  "propertyProfile": {
    "densityMilli": 50000,
    "complexityMilli": 33333,
    "syncopationMilli": 0,
    "evennessMilli": 100000,
    "occupancyMilli": 83333,
    "diversityMilli": 91829
  },
  "curveMisses": [
    {
      "property": "syncopation",
      "gapMilli": 12345,
      "reason": "projection"
    }
  ]
};
