// GENERATED by `cargo test -p cseq-app dto_fixture` (UPDATE_DTO_FIXTURES=1).
// Do not edit by hand. This literal is the serialized Rust DTO; the type
// annotation makes `pnpm typecheck` the Rust↔TS drift gate.
import type { MachinePrefsSnapshot } from "../../bridge";

export const machinePrefsSnapshotFixture: MachinePrefsSnapshot = {
  "prefs": {
    "prefsVersion": 1,
    "midiDestination": {
      "id": "-673416519",
      "name": "IAC Driver Bus 1"
    },
    "autosaveEnabled": true,
    "autosaveIntervalMs": 3000,
    "autoloadRecentSession": true
  },
  "source": "file"
};
