// GENERATED by `cargo test -p cseq-app dto_fixture` (UPDATE_DTO_FIXTURES=1).
// Do not edit by hand. This literal is the serialized Rust DTO; the type
// annotation makes `pnpm typecheck` the Rust↔TS drift gate.
import type { MidiRouteStatus } from "../../bridge";

export const midiRouteStatusFixture: MidiRouteStatus = {
  "desired": {
    "id": "-673416519",
    "name": "IAC Driver Bus 1"
  },
  "connected": false,
  "lastError": "destination not present"
};
