// GENERATED by `cargo test -p cseq-app dto_fixture` (UPDATE_DTO_FIXTURES=1).
// Do not edit by hand. This literal is the serialized Rust DTO; the type
// annotation makes `pnpm typecheck` the Rust↔TS drift gate.
import type { SubdivisionSwitchPreview } from "../../bridge";

export const subdivisionSwitchPreviewFixture: SubdivisionSwitchPreview = {
  "cycle": 0,
  "beats": [
    {
      "beat": 1,
      "start": 0.0,
      "end": 0.16666666666666666,
      "gati": 7,
      "effectiveGati": 7,
      "sectionIndex": 1,
      "jathi": 3,
      "sectionStart": true,
      "accentVelocity": 110,
      "pitch": 60,
      "baseVelocity": 96,
      "automationPhase": {
        "numer": 0,
        "denom": 1
      },
      "automationValues": []
    },
    {
      "beat": 2,
      "start": 0.16666666666666666,
      "end": 0.3333333333333333,
      "gati": 7,
      "effectiveGati": 7,
      "sectionIndex": 1,
      "jathi": 3,
      "sectionStart": false,
      "accentVelocity": 100,
      "pitch": 60,
      "baseVelocity": 96,
      "automationPhase": {
        "numer": 1,
        "denom": 6
      },
      "automationValues": []
    },
    {
      "beat": 3,
      "start": 0.3333333333333333,
      "end": 0.5,
      "gati": 7,
      "effectiveGati": 7,
      "sectionIndex": 1,
      "jathi": 3,
      "sectionStart": false,
      "accentVelocity": 100,
      "pitch": 60,
      "baseVelocity": 96,
      "automationPhase": {
        "numer": 1,
        "denom": 3
      },
      "automationValues": []
    },
    {
      "beat": 4,
      "start": 0.5,
      "end": 0.6666666666666666,
      "gati": 7,
      "effectiveGati": 7,
      "sectionIndex": 2,
      "jathi": 3,
      "sectionStart": true,
      "accentVelocity": 110,
      "pitch": 60,
      "baseVelocity": 96,
      "automationPhase": {
        "numer": 1,
        "denom": 2
      },
      "automationValues": []
    },
    {
      "beat": 5,
      "start": 0.6666666666666666,
      "end": 0.8333333333333333,
      "gati": 7,
      "effectiveGati": 7,
      "sectionIndex": 2,
      "jathi": 3,
      "sectionStart": false,
      "accentVelocity": 100,
      "pitch": 60,
      "baseVelocity": 96,
      "automationPhase": {
        "numer": 2,
        "denom": 3
      },
      "automationValues": []
    },
    {
      "beat": 6,
      "start": 0.8333333333333334,
      "end": 1.0,
      "gati": 7,
      "effectiveGati": 7,
      "sectionIndex": 2,
      "jathi": 3,
      "sectionStart": false,
      "accentVelocity": 100,
      "pitch": 60,
      "baseVelocity": 96,
      "automationPhase": {
        "numer": 5,
        "denom": 6
      },
      "automationValues": []
    }
  ],
  "pulseSpans": [
    {
      "id": 0,
      "kind": "section",
      "sectionIndex": 1,
      "beat": null,
      "gati": null,
      "jathi": null,
      "index": null,
      "start": 0.0,
      "duration": 3.0,
      "startMatra": 0,
      "matraLen": 21,
      "subdivision": 7,
      "protectedCuts": [],
      "tags": [
        "section",
        "protected-accent-span"
      ],
      "matraVelocities": []
    },
    {
      "id": 1,
      "kind": "gatiBeat",
      "sectionIndex": 1,
      "beat": 1,
      "gati": 7,
      "jathi": null,
      "index": null,
      "start": 0.0,
      "duration": 1.0,
      "startMatra": 0,
      "matraLen": 7,
      "subdivision": 7,
      "protectedCuts": [],
      "tags": [
        "gati-beat",
        "protected-accent-span"
      ],
      "matraVelocities": [
        110,
        96,
        96,
        102,
        96,
        96,
        102
      ]
    },
    {
      "id": 2,
      "kind": "gatiBeat",
      "sectionIndex": 1,
      "beat": 2,
      "gati": 7,
      "jathi": null,
      "index": null,
      "start": 1.0,
      "duration": 1.0,
      "startMatra": 7,
      "matraLen": 7,
      "subdivision": 7,
      "protectedCuts": [],
      "tags": [
        "gati-beat",
        "protected-accent-span"
      ],
      "matraVelocities": [
        100,
        96,
        102,
        96,
        96,
        102,
        96
      ]
    },
    {
      "id": 3,
      "kind": "gatiBeat",
      "sectionIndex": 1,
      "beat": 3,
      "gati": 7,
      "jathi": null,
      "index": null,
      "start": 2.0,
      "duration": 1.0,
      "startMatra": 14,
      "matraLen": 7,
      "subdivision": 7,
      "protectedCuts": [],
      "tags": [
        "gati-beat",
        "protected-accent-span"
      ],
      "matraVelocities": [
        100,
        102,
        96,
        96,
        102,
        96,
        96
      ]
    },
    {
      "id": 4,
      "kind": "jathiPulse",
      "sectionIndex": 1,
      "beat": null,
      "gati": null,
      "jathi": 3,
      "index": 1,
      "start": 0.0,
      "duration": 0.42857142857142855,
      "startMatra": 0,
      "matraLen": 3,
      "subdivision": 7,
      "protectedCuts": [],
      "tags": [
        "jathi-pulse",
        "protected-accent-span"
      ],
      "matraVelocities": [
        110,
        96,
        96
      ]
    },
    {
      "id": 5,
      "kind": "jathiPulse",
      "sectionIndex": 1,
      "beat": null,
      "gati": null,
      "jathi": 3,
      "index": 2,
      "start": 0.42857142857142855,
      "duration": 0.42857142857142855,
      "startMatra": 3,
      "matraLen": 3,
      "subdivision": 7,
      "protectedCuts": [],
      "tags": [
        "jathi-pulse",
        "protected-accent-span"
      ],
      "matraVelocities": [
        102,
        96,
        96
      ]
    },
    {
      "id": 6,
      "kind": "jathiPulse",
      "sectionIndex": 1,
      "beat": null,
      "gati": null,
      "jathi": 3,
      "index": 3,
      "start": 0.8571428571428571,
      "duration": 0.42857142857142855,
      "startMatra": 6,
      "matraLen": 3,
      "subdivision": 7,
      "protectedCuts": [],
      "tags": [
        "jathi-pulse",
        "protected-accent-span"
      ],
      "matraVelocities": [
        102,
        100,
        96
      ]
    },
    {
      "id": 7,
      "kind": "jathiPulse",
      "sectionIndex": 1,
      "beat": null,
      "gati": null,
      "jathi": 3,
      "index": 4,
      "start": 1.2857142857142858,
      "duration": 0.42857142857142855,
      "startMatra": 9,
      "matraLen": 3,
      "subdivision": 7,
      "protectedCuts": [],
      "tags": [
        "jathi-pulse",
        "protected-accent-span"
      ],
      "matraVelocities": [
        102,
        96,
        96
      ]
    },
    {
      "id": 8,
      "kind": "jathiPulse",
      "sectionIndex": 1,
      "beat": null,
      "gati": null,
      "jathi": 3,
      "index": 5,
      "start": 1.7142857142857142,
      "duration": 0.42857142857142855,
      "startMatra": 12,
      "matraLen": 3,
      "subdivision": 7,
      "protectedCuts": [],
      "tags": [
        "jathi-pulse",
        "protected-accent-span"
      ],
      "matraVelocities": [
        102,
        96,
        100
      ]
    },
    {
      "id": 9,
      "kind": "jathiPulse",
      "sectionIndex": 1,
      "beat": null,
      "gati": null,
      "jathi": 3,
      "index": 6,
      "start": 2.142857142857143,
      "duration": 0.42857142857142855,
      "startMatra": 15,
      "matraLen": 3,
      "subdivision": 7,
      "protectedCuts": [],
      "tags": [
        "jathi-pulse",
        "protected-accent-span"
      ],
      "matraVelocities": [
        102,
        96,
        96
      ]
    },
    {
      "id": 10,
      "kind": "jathiPulse",
      "sectionIndex": 1,
      "beat": null,
      "gati": null,
      "jathi": 3,
      "index": 7,
      "start": 2.5714285714285716,
      "duration": 0.42857142857142855,
      "startMatra": 18,
      "matraLen": 3,
      "subdivision": 7,
      "protectedCuts": [],
      "tags": [
        "jathi-pulse",
        "protected-accent-span"
      ],
      "matraVelocities": [
        102,
        96,
        96
      ]
    },
    {
      "id": 11,
      "kind": "section",
      "sectionIndex": 2,
      "beat": null,
      "gati": null,
      "jathi": null,
      "index": null,
      "start": 3.0,
      "duration": 3.0,
      "startMatra": 0,
      "matraLen": 21,
      "subdivision": 7,
      "protectedCuts": [],
      "tags": [
        "section",
        "protected-accent-span"
      ],
      "matraVelocities": []
    },
    {
      "id": 12,
      "kind": "gatiBeat",
      "sectionIndex": 2,
      "beat": 4,
      "gati": 7,
      "jathi": null,
      "index": null,
      "start": 3.0,
      "duration": 1.0,
      "startMatra": 0,
      "matraLen": 7,
      "subdivision": 7,
      "protectedCuts": [],
      "tags": [
        "gati-beat",
        "protected-accent-span"
      ],
      "matraVelocities": [
        110,
        96,
        96,
        102,
        96,
        96,
        102
      ]
    },
    {
      "id": 13,
      "kind": "gatiBeat",
      "sectionIndex": 2,
      "beat": 5,
      "gati": 7,
      "jathi": null,
      "index": null,
      "start": 4.0,
      "duration": 1.0,
      "startMatra": 7,
      "matraLen": 7,
      "subdivision": 7,
      "protectedCuts": [],
      "tags": [
        "gati-beat",
        "protected-accent-span"
      ],
      "matraVelocities": [
        100,
        96,
        102,
        96,
        96,
        102,
        96
      ]
    },
    {
      "id": 14,
      "kind": "gatiBeat",
      "sectionIndex": 2,
      "beat": 6,
      "gati": 7,
      "jathi": null,
      "index": null,
      "start": 5.0,
      "duration": 1.0,
      "startMatra": 14,
      "matraLen": 7,
      "subdivision": 7,
      "protectedCuts": [],
      "tags": [
        "gati-beat",
        "protected-accent-span"
      ],
      "matraVelocities": [
        100,
        102,
        96,
        96,
        102,
        96,
        96
      ]
    },
    {
      "id": 15,
      "kind": "jathiPulse",
      "sectionIndex": 2,
      "beat": null,
      "gati": null,
      "jathi": 3,
      "index": 1,
      "start": 3.0,
      "duration": 0.42857142857142855,
      "startMatra": 0,
      "matraLen": 3,
      "subdivision": 7,
      "protectedCuts": [],
      "tags": [
        "jathi-pulse",
        "protected-accent-span"
      ],
      "matraVelocities": [
        110,
        96,
        96
      ]
    },
    {
      "id": 16,
      "kind": "jathiPulse",
      "sectionIndex": 2,
      "beat": null,
      "gati": null,
      "jathi": 3,
      "index": 2,
      "start": 3.4285714285714284,
      "duration": 0.42857142857142855,
      "startMatra": 3,
      "matraLen": 3,
      "subdivision": 7,
      "protectedCuts": [],
      "tags": [
        "jathi-pulse",
        "protected-accent-span"
      ],
      "matraVelocities": [
        102,
        96,
        96
      ]
    },
    {
      "id": 17,
      "kind": "jathiPulse",
      "sectionIndex": 2,
      "beat": null,
      "gati": null,
      "jathi": 3,
      "index": 3,
      "start": 3.857142857142857,
      "duration": 0.42857142857142855,
      "startMatra": 6,
      "matraLen": 3,
      "subdivision": 7,
      "protectedCuts": [],
      "tags": [
        "jathi-pulse",
        "protected-accent-span"
      ],
      "matraVelocities": [
        102,
        100,
        96
      ]
    },
    {
      "id": 18,
      "kind": "jathiPulse",
      "sectionIndex": 2,
      "beat": null,
      "gati": null,
      "jathi": 3,
      "index": 4,
      "start": 4.285714285714286,
      "duration": 0.42857142857142855,
      "startMatra": 9,
      "matraLen": 3,
      "subdivision": 7,
      "protectedCuts": [],
      "tags": [
        "jathi-pulse",
        "protected-accent-span"
      ],
      "matraVelocities": [
        102,
        96,
        96
      ]
    },
    {
      "id": 19,
      "kind": "jathiPulse",
      "sectionIndex": 2,
      "beat": null,
      "gati": null,
      "jathi": 3,
      "index": 5,
      "start": 4.714285714285714,
      "duration": 0.42857142857142855,
      "startMatra": 12,
      "matraLen": 3,
      "subdivision": 7,
      "protectedCuts": [],
      "tags": [
        "jathi-pulse",
        "protected-accent-span"
      ],
      "matraVelocities": [
        102,
        96,
        100
      ]
    },
    {
      "id": 20,
      "kind": "jathiPulse",
      "sectionIndex": 2,
      "beat": null,
      "gati": null,
      "jathi": 3,
      "index": 6,
      "start": 5.142857142857143,
      "duration": 0.42857142857142855,
      "startMatra": 15,
      "matraLen": 3,
      "subdivision": 7,
      "protectedCuts": [],
      "tags": [
        "jathi-pulse",
        "protected-accent-span"
      ],
      "matraVelocities": [
        102,
        96,
        96
      ]
    },
    {
      "id": 21,
      "kind": "jathiPulse",
      "sectionIndex": 2,
      "beat": null,
      "gati": null,
      "jathi": 3,
      "index": 7,
      "start": 5.571428571428571,
      "duration": 0.42857142857142855,
      "startMatra": 18,
      "matraLen": 3,
      "subdivision": 7,
      "protectedCuts": [],
      "tags": [
        "jathi-pulse",
        "protected-accent-span"
      ],
      "matraVelocities": [
        102,
        96,
        96
      ]
    }
  ],
  "historySeeds": [
    "9007199254740993",
    "18446744073709551615"
  ]
};
