// GENERATED by `cargo test -p cseq-app dto_fixture` (UPDATE_DTO_FIXTURES=1).
// Do not edit by hand. This literal is the serialized Rust DTO; the type
// annotation makes `pnpm typecheck` the Rust↔TS drift gate.
import type { TransportSnapshot } from "../../bridge";

export const transportSnapshotFixture: TransportSnapshot = {
  "sampleEpoch": 0,
  "timelineEpoch": 0,
  "logEpoch": 0,
  "tempoBpm": 92.5,
  "isPlaying": true,
  "currentTick": 1234,
  "currentCycle": 3,
  "ticksPerCycle": 3840,
  "currentScoreId": "fixture-score",
  "parallelTrackPositions": [
    {
      "trackIndex": 0,
      "trackId": "track-1",
      "trackName": "Lead",
      "cycle": 3,
      "tickInCycle": 1234,
      "ticksPerCycle": 3840,
      "referenceStartTick": 11520,
      "referenceEndTick": 15360
    }
  ],
  "midiDebugEvents": [
    {
      "sequence": 7,
      "absoluteTick": 12754,
      "cycle": 3,
      "tickInCycle": 1234,
      "channel": 1,
      "messageType": "noteOn",
      "data1": 60,
      "data2": 96,
      "bytes": [
        144,
        60,
        96
      ],
      "debugSource": "queued dispatch",
      "monitorBus": "bus 1",
      "monitorUserChannel": 1,
      "monitorMode": "melodic",
      "monitorProgram": 0,
      "monitorDrumNote": 38,
      "monitorBytes": [
        144,
        60,
        96
      ],
      "parallelTrackId": "track-1",
      "parallelTrackName": "Lead",
      "parallelConflictPolicy": "allowAll",
      "parallelConflictAction": "priority-winner",
      "parallelConflictGroupId": "12754:1"
    }
  ],
  "automationEvents": [
    {
      "sequence": 5,
      "cycle": 3,
      "beatIndex": 1,
      "tickInCycle": 960,
      "automationPhase": {
        "numer": 13,
        "denom": 4
      },
      "values": [
        {
          "target": "transport.tempoBpm",
          "value": 92.5
        }
      ]
    }
  ],
  "channelHocketEvents": [
    {
      "cycle": 3,
      "startTick": 960,
      "endTick": 1920,
      "channel": 2,
      "source": "transition",
      "fallback": false,
      "positionRuleId": null,
      "positionRuleLabel": null,
      "positionScope": null,
      "positionNth": null,
      "positionAction": null,
      "parallelTrackIndex": 0,
      "parallelTrackId": "track-1",
      "parallelTrackName": "Lead",
      "suppressed": false
    }
  ],
  "seedTraceEvents": [
    {
      "cycle": 3,
      "domain": "subdivision",
      "label": "Subdivision switch",
      "seed": "9007199254740993",
      "baseSeed": "18446744073709551615",
      "source": "perCycle",
      "historyBefore": [
        "9007199254740992",
        "9007199254740993"
      ],
      "historyAfter": [
        "9007199254740992",
        "9007199254740993",
        "18446744073709551615"
      ],
      "parallelTrackIndex": 0,
      "trackId": "track-1"
    }
  ],
  "parallelConflictEvents": [
    {
      "sequence": 2,
      "absoluteTick": 12480,
      "cycle": 3,
      "tickInCycle": 960,
      "outputChannel": 1,
      "pitch": 60,
      "startTick": 12480,
      "endTick": 12600,
      "trackId": "track-2",
      "trackName": "Follower",
      "trackIndex": 1,
      "conflictPolicy": "allowAll",
      "conflictAction": "priority-suppress",
      "conflictGroupId": "12480:1",
      "collidingTrackIds": [
        "track-1",
        "track-2"
      ],
      "activeTrackCount": 2,
      "passed": false
    }
  ],
  "triggerDecisionEvents": [
    {
      "trackIndex": 1,
      "trackId": "track-2",
      "trackName": "Follower",
      "sourceCycleIndex": 3,
      "matchedBeat": 2,
      "eventTick": 12480,
      "candidateTick": 12480,
      "startKind": "atEvent",
      "outcome": "launched",
      "suppressReason": "gateProbability",
      "launchTick": 12480,
      "runIndex": 3,
      "rollValue": 412,
      "rollThreshold": 500,
      "rollPassed": true,
      "consecutiveMisses": 0,
      "lastAcceptSourceCycle": 2
    }
  ],
  "realizedRhythmEvents": [
    {
      "cycle": 3,
      "parallelTrackIndex": 0,
      "parallelTrackId": "track-1",
      "span": {
        "spanId": 5,
        "spanLen": 4,
        "cells": [
          {
            "index": 0,
            "start": 0,
            "len": 2,
            "rest": false,
            "tiedFromPrevious": false,
            "tiedToNext": false,
            "velocity": 125
          },
          {
            "index": 1,
            "start": 2,
            "len": 2,
            "rest": true,
            "tiedFromPrevious": false,
            "tiedToNext": false,
            "velocity": 96
          }
        ]
      }
    }
  ],
  "trackFlowEvents": [
    {
      "cycle": 3,
      "referenceStartTick": 11520,
      "laneId": "track-flow-main",
      "sourceTrackId": "track-2",
      "sourceTrackName": "Track 2"
    }
  ]
};
